"""Distribute + connect the browser capture extension.

The recruiter downloads the extension from here and connects it with a personal
capture token; the extension then POSTs candidates it captures on Indeed (and,
soon, other platforms) to /api/ingest/* as that recruiter.
"""
from __future__ import annotations

import io
import secrets
import zipfile
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import Response

from ..deps import CurrentUser, DbSession
from ..models import User  # noqa: F401 (kept for clarity; User comes via CurrentUser)

router = APIRouter(prefix="/api/extension", tags=["extension"])

# The packaged Chrome/Edge extension (MV3) lives beside the job board.
_EXT_DIR = (Path(__file__).resolve().parent.parent.parent
            / "Radixsol_Sourcing_Assistant" / "src_pkg" / "frontend")
_VERSION = "2.5.2"
_PLATFORMS = [
    {"name": "Indeed", "status": "live"},
    {"name": "Vivian", "status": "coming"},
    {"name": "ZipRecruiter", "status": "coming"},
    {"name": "Facebook", "status": "coming"},
]


def _require_recruiter(user: CurrentUser) -> None:
    if user.role.value not in {"recruiter", "admin"}:
        raise HTTPException(status_code=403,
                            detail="The capture extension is available to recruiter accounts.")


def _ensure_token(db, user: User) -> str:
    if not user.capture_token:
        user.capture_token = secrets.token_urlsafe(32)
        db.commit()
    return user.capture_token


@router.get("/connect")
def connect(request: Request, user: CurrentUser, db: DbSession):
    """Everything the extension needs to talk to this job board as this recruiter."""
    _require_recruiter(user)
    return {
        "api_base": str(request.base_url).rstrip("/"),
        "capture_token": _ensure_token(db, user),
        "recruiter_email": user.email,
        "version": _VERSION,
        "platforms": _PLATFORMS,
    }


@router.post("/token")
def rotate_token(user: CurrentUser, db: DbSession):
    """Issue a fresh capture token (revokes the old one)."""
    _require_recruiter(user)
    user.capture_token = secrets.token_urlsafe(32)
    db.commit()
    return {"capture_token": user.capture_token}


@router.get("/download")
def download(request: Request, user: CurrentUser, db: DbSession):
    """Package the extension as a .zip, with this job board's URL baked in."""
    _require_recruiter(user)
    if not _EXT_DIR.is_dir():
        raise HTTPException(status_code=404, detail="Extension package is unavailable.")
    api_base = str(request.base_url).rstrip("/")
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(_EXT_DIR.iterdir()):
            if f.is_file() and not f.name.startswith("."):
                z.write(f, f.name)
        # Connection config the extension reads to reach this job board.
        z.writestr("jobboard-config.js",
                   "// Generated by HealthBoard — connects the extension to your job board.\n"
                   f'window.HEALTHBOARD = {{ apiBase: "{api_base}", '
                   'ingestPath: "/api/ingest/candidate", resumePath: "/api/ingest/resume" }};\n')
    return Response(
        content=buf.getvalue(),
        media_type="application/zip",
        headers={"Content-Disposition": 'attachment; filename="healthboard-capture-extension.zip"'},
    )
