"""Create a contact-enriched copy of a captured candidate resume.

The source resume pages are kept unchanged.  A Radixsol contact page is
prepended using the contact data already committed to the candidate record.
"""
from __future__ import annotations

from io import BytesIO
from pathlib import Path


def _clean_values(values, limit: int = 5) -> list[str]:
    output: list[str] = []
    seen: set[str] = set()
    for value in values or []:
        cleaned = str(value or "").strip()
        key = cleaned.casefold()
        if not cleaned or key in seen:
            continue
        seen.add(key)
        output.append(cleaned)
        if len(output) >= limit:
            break
    return output


def enriched_filename(filename: str) -> str:
    source = Path(filename or "resume.pdf")
    stem = source.stem.strip() or "resume"
    if stem.casefold().endswith(" - enriched"):
        return f"{stem}.pdf"
    return f"{stem} - enriched.pdf"


def add_contact_sheet(data: bytes, candidate: dict) -> tuple[bytes, bool]:
    """Return ``(pdf_bytes, embedded)`` for a captured PDF.

    Invalid/non-standard test fixtures are returned unchanged. Real Indeed
    PDFs are parsed and receive a new first page containing matched contact
    details. This preserves the source pages exactly as received.
    """
    phones = _clean_values(candidate.get("phones"))
    emails = _clean_values(candidate.get("emails"))
    if not phones and not emails:
        return data, False

    try:
        from pypdf import PdfReader, PdfWriter
        from reportlab.lib.colors import HexColor
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas

        source_reader = PdfReader(BytesIO(data), strict=False)
        if not source_reader.pages:
            return data, False

        contact_buffer = BytesIO()
        # Keep retry output deterministic so an identical capture can be
        # recognized by checksum instead of creating another stored version.
        page = canvas.Canvas(contact_buffer, pagesize=letter, invariant=1)
        width, height = letter
        purple = HexColor("#7432F4")
        dark = HexColor("#151B2B")
        muted = HexColor("#5F6F89")

        page.setFillColor(purple)
        page.rect(0, height - 112, width, 112, stroke=0, fill=1)
        page.setFillColorRGB(1, 1, 1)
        page.setFont("Helvetica-Bold", 23)
        page.drawString(42, height - 64, "Radixsol Candidate Contact")
        page.setFont("Helvetica", 10)
        page.drawString(42, height - 86, "Matched contact data attached to the original Indeed resume")

        y = height - 158
        page.setFillColor(dark)
        page.setFont("Helvetica-Bold", 19)
        page.drawString(42, y, str(candidate.get("name") or "Candidate")[:100])
        y -= 24
        location = str(candidate.get("location") or "").strip()
        if location:
            page.setFillColor(muted)
            page.setFont("Helvetica", 11)
            page.drawString(42, y, location[:120])
            y -= 38
        else:
            y -= 18

        def section(label: str, values: list[str]) -> None:
            nonlocal y
            page.setFillColor(purple)
            page.setFont("Helvetica-Bold", 11)
            page.drawString(42, y, label.upper())
            y -= 21
            page.setFillColor(dark)
            page.setFont("Helvetica", 12)
            if values:
                for value in values:
                    page.drawString(56, y, value[:120])
                    y -= 20
            else:
                page.setFillColor(muted)
                page.drawString(56, y, "Not available")
                y -= 20
            y -= 20

        section("Email", emails)
        section("Phone", phones)

        verification = candidate.get("verification") or {}
        provider = str(verification.get("source") or "candidate enrichment").strip()
        confidence = float(candidate.get("confidence") or 0)
        page.setFillColor(muted)
        page.setFont("Helvetica", 9)
        page.drawString(42, 91, f"Contact source: {provider[:60]}")
        if confidence > 0:
            page.drawString(42, 76, f"Identity-match confidence: {round(confidence * 100)}%")
        page.drawString(
            42,
            61,
            "The original resume follows unchanged. Contact ownership/deliverability may require separate verification.",
        )
        page.drawString(42, 46, "Generated by Radixsol Sourcing Assistant")
        page.save()
        contact_buffer.seek(0)

        writer = PdfWriter()
        writer.add_page(PdfReader(contact_buffer).pages[0])
        for source_page in source_reader.pages:
            writer.add_page(source_page)
        writer.add_metadata({
            "/Title": f"{candidate.get('name') or 'Candidate'} - Enriched Resume",
            "/Author": "Radixsol Sourcing Assistant",
            "/RadixsolCandidateId": str(candidate.get("id") or ""),
            "/RadixsolEmails": "; ".join(emails),
            "/RadixsolPhones": "; ".join(phones),
        })
        output = BytesIO()
        writer.write(output)
        enriched = output.getvalue()
        return (enriched, True) if enriched.startswith(b"%PDF-") else (data, False)
    except Exception:
        # Resume capture must remain available for unusual PDFs. The caller
        # reports whether a contact sheet was embedded so it is never implied
        # that an untouched fallback contains contact data.
        return data, False
