"""initial schema

Revision ID: e9e3e290bcba
Revises: 
Create Date: 2026-05-30 00:54:47.228019
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e3e290bcba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('job_seeker', 'employer', 'recruiter', 'admin', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', 'pending_verify', name='userstatus'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_last_login_at'), ['last_login_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    op.create_table('email_verification_tokens',
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('employers',
    sa.Column('employer_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('org_name', sa.String(length=300), nullable=False),
    sa.Column('org_type', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('bed_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('subscription_tier', sa.Enum('free', 'basic', 'pro', 'enterprise', name='subscriptiontier'), nullable=False),
    sa.Column('job_credits_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employer_id')
    )
    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employers_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_employers_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_employers_org_type'), ['org_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_employers_state_code'), ['state_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_employers_subscription_tier'), ['subscription_tier'], unique=False)

    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('message', 'application', 'connection', 'job_match', 'system', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)

    op.create_table('oauth_accounts',
    sa.Column('oauth_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=2048), nullable=True),
    sa.Column('refresh_token', sa.String(length=2048), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oauth_id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_provider_user')
    )
    op.create_table('password_reset_tokens',
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('profiles',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('profession_type', sa.String(length=50), nullable=True),
    sa.Column('years_experience', sa.SmallInteger(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('open_to_work', sa.Boolean(), nullable=False),
    sa.Column('job_type_prefs', sa.JSON(), nullable=False),
    sa.Column('pay_min_hourly', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('available_date', sa.Date(), nullable=True),
    sa.Column('npi_number', sa.String(length=10), nullable=True),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('resume_url', sa.Text(), nullable=True),
    sa.Column('completion_score', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.Enum('signup', 'json_import', 'resume_parse', 'manual', name='profilesource'), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('npi_number')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_available_date'), ['available_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_completion_score'), ['completion_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_open_to_work'), ['open_to_work'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_pay_min_hourly'), ['pay_min_hourly'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_profession_type'), ['profession_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_search_text'), ['search_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_specialty'), ['specialty'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_state_code'), ['state_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)

    op.create_table('certifications',
    sa.Column('cert_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('cert_name', sa.String(length=100), nullable=False),
    sa.Column('issuing_body', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('cert_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cert_id')
    )
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certifications_cert_name'), ['cert_name'], unique=False)

    op.create_table('connections',
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('requester_profile_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_profile_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'blocked', name='connectionstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connection_id'),
    sa.UniqueConstraint('requester_profile_id', 'recipient_profile_id', name='uq_connection_pair')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connections_status'), ['status'], unique=False)

    op.create_table('employer_members',
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('employer_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('member_role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.employer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('employer_id', 'user_id', name='uq_employer_member')
    )
    op.create_table('job_postings',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('employer_id', sa.String(length=36), nullable=False),
    sa.Column('posted_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('profession_type', sa.String(length=50), nullable=True),
    sa.Column('job_type', sa.Enum('travel', 'staff', 'per_diem', 'contract', name='jobtype'), nullable=False),
    sa.Column('shift_type', sa.String(length=50), nullable=True),
    sa.Column('pay_rate_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pay_rate_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pay_unit', sa.String(length=20), nullable=False),
    sa.Column('housing_stipend', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('signing_bonus', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('benefits', sa.JSON(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('required_certifications', sa.JSON(), nullable=False),
    sa.Column('years_exp_min', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'closed', 'expired', name='jobstatus'), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('application_count', sa.Integer(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.employer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_postings_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_is_urgent'), ['is_urgent'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_pay_rate_max'), ['pay_rate_max'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_pay_rate_min'), ['pay_rate_min'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_profession_type'), ['profession_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_search_text'), ['search_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_shift_type'), ['shift_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_specialty'), ['specialty'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_state_code'), ['state_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_status'), ['status'], unique=False)

    op.create_table('licenses',
    sa.Column('license_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('license_type', sa.String(length=50), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'suspended', 'pending', name='licensestatus'), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_source', sa.String(length=100), nullable=True),
    sa.Column('is_compact', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('license_id')
    )
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licenses_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_licenses_license_number'), ['license_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_licenses_license_type'), ['license_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_licenses_state_code'), ['state_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_licenses_status'), ['status'], unique=False)

    op.create_table('posts',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('author_profile_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media_urls', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('profile_skills',
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('years', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id')
    )
    with op.batch_alter_table('profile_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_skills_name'), ['name'], unique=False)

    op.create_table('work_history',
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('employer_name', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bed_count', sa.SmallInteger(), nullable=True),
    sa.Column('nurse_ratio', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_id')
    )
    with op.batch_alter_table('work_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_history_specialty'), ['specialty'], unique=False)

    op.create_table('applications',
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('applied', 'screening', 'interview', 'offer', 'hired', 'rejected', 'withdrawn', name='applicationstatus'), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('resume_snapshot_url', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recruiter_notes', sa.Text(), nullable=True),
    sa.Column('recruiter_rating', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.job_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('job_id', 'profile_id', name='uq_application_job_profile')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_match_score'), ['match_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    op.create_table('match_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('job_spec', sa.JSON(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.job_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('message_threads',
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('participant_a_id', sa.String(length=36), nullable=False),
    sa.Column('participant_b_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('ats_stage', sa.String(length=50), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.job_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participant_a_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_b_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id')
    )
    with op.batch_alter_table('message_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_threads_last_message_at'), ['last_message_at'], unique=False)

    op.create_table('pay_packages',
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.job_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('package_id')
    )
    op.create_table('post_comments',
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('author_profile_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('post_likes',
    sa.Column('like_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('like_id'),
    sa.UniqueConstraint('post_id', 'profile_id', name='uq_post_like')
    )
    op.create_table('saved_jobs',
    sa.Column('save_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.job_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('save_id'),
    sa.UniqueConstraint('profile_id', 'job_id', name='uq_saved_job')
    )
    op.create_table('application_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('interviews',
    sa.Column('interview_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('recruiter_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'confirmed', 'completed', 'cancelled', name='interviewstatus'), nullable=False),
    sa.Column('proposed_slots', sa.JSON(), nullable=False),
    sa.Column('confirmed_slot', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.job_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.thread_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('interview_id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_status'), ['status'], unique=False)

    op.create_table('match_results',
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('score_skills', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_experience', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_location', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_pay', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('shortlisted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['match_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('text', 'job_card', 'schedule', 'offer', 'system', name='messagekind'), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.thread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_is_read'), ['is_read'], unique=False)

    op.create_table('offers',
    sa.Column('offer_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=True),
    sa.Column('recruiter_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('sent', 'accepted', 'declined', 'expired', name='offerstatus'), nullable=False),
    sa.Column('pay_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pay_unit', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.job_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.thread_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('offer_id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_status'))

    op.drop_table('offers')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_is_read'))

    op.drop_table('messages')
    op.drop_table('match_results')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_status'))

    op.drop_table('interviews')
    op.drop_table('application_events')
    op.drop_table('saved_jobs')
    op.drop_table('post_likes')
    op.drop_table('post_comments')
    op.drop_table('pay_packages')
    with op.batch_alter_table('message_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_threads_last_message_at'))

    op.drop_table('message_threads')
    op.drop_table('match_runs')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_source'))
        batch_op.drop_index(batch_op.f('ix_applications_match_score'))

    op.drop_table('applications')
    with op.batch_alter_table('work_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_history_specialty'))

    op.drop_table('work_history')
    with op.batch_alter_table('profile_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_skills_name'))

    op.drop_table('profile_skills')
    op.drop_table('posts')
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licenses_status'))
        batch_op.drop_index(batch_op.f('ix_licenses_state_code'))
        batch_op.drop_index(batch_op.f('ix_licenses_license_type'))
        batch_op.drop_index(batch_op.f('ix_licenses_license_number'))
        batch_op.drop_index(batch_op.f('ix_licenses_expiry_date'))

    op.drop_table('licenses')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_postings_status'))
        batch_op.drop_index(batch_op.f('ix_job_postings_state_code'))
        batch_op.drop_index(batch_op.f('ix_job_postings_specialty'))
        batch_op.drop_index(batch_op.f('ix_job_postings_shift_type'))
        batch_op.drop_index(batch_op.f('ix_job_postings_search_text'))
        batch_op.drop_index(batch_op.f('ix_job_postings_profession_type'))
        batch_op.drop_index(batch_op.f('ix_job_postings_pay_rate_min'))
        batch_op.drop_index(batch_op.f('ix_job_postings_pay_rate_max'))
        batch_op.drop_index(batch_op.f('ix_job_postings_job_type'))
        batch_op.drop_index(batch_op.f('ix_job_postings_is_urgent'))
        batch_op.drop_index(batch_op.f('ix_job_postings_is_featured'))
        batch_op.drop_index(batch_op.f('ix_job_postings_expires_at'))
        batch_op.drop_index(batch_op.f('ix_job_postings_city'))

    op.drop_table('job_postings')
    op.drop_table('employer_members')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connections_status'))

    op.drop_table('connections')
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certifications_cert_name'))

    op.drop_table('certifications')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_profiles_state_code'))
        batch_op.drop_index(batch_op.f('ix_profiles_specialty'))
        batch_op.drop_index(batch_op.f('ix_profiles_source'))
        batch_op.drop_index(batch_op.f('ix_profiles_search_text'))
        batch_op.drop_index(batch_op.f('ix_profiles_profession_type'))
        batch_op.drop_index(batch_op.f('ix_profiles_pay_min_hourly'))
        batch_op.drop_index(batch_op.f('ix_profiles_open_to_work'))
        batch_op.drop_index(batch_op.f('ix_profiles_completion_score'))
        batch_op.drop_index(batch_op.f('ix_profiles_city'))
        batch_op.drop_index(batch_op.f('ix_profiles_available_date'))

    op.drop_table('profiles')
    op.drop_table('password_reset_tokens')
    op.drop_table('oauth_accounts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employers_subscription_tier'))
        batch_op.drop_index(batch_op.f('ix_employers_state_code'))
        batch_op.drop_index(batch_op.f('ix_employers_org_type'))
        batch_op.drop_index(batch_op.f('ix_employers_is_verified'))
        batch_op.drop_index(batch_op.f('ix_employers_city'))

    op.drop_table('employers')
    op.drop_table('email_verification_tokens')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_last_login_at'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
